// This file is used by Code Analysis to maintain SuppressMessage 
// attributes that are applied to this project. 
// Project-level suppressions either have no target or are given 
// a specific target and scoped to a namespace, type, member, etc. 
//
// To add a suppression to this file, right-click the message in the 
// Error List, point to "Suppress Message(s)", and click 
// "In Project Suppression File". 
// You do not need to add suppressions to this file manually. 

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage( "Microsoft.Performance", "CA1822:MarkMembersAsStatic", Scope = "member", Target = "LiveCapture.CommObj.#connectCSV(System.String,System.String)" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage( "Microsoft.Design", "CA1044:PropertiesShouldNotBeWriteOnly", Scope = "member", Target = "LiveCapture.SMTPSender.#mailBCC" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage( "Microsoft.Design", "CA1044:PropertiesShouldNotBeWriteOnly", Scope = "member", Target = "LiveCapture.SMTPSender.#mailBody" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage( "Microsoft.Design", "CA1044:PropertiesShouldNotBeWriteOnly", Scope = "member", Target = "LiveCapture.SMTPSender.#mailCC" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage( "Microsoft.Design", "CA1044:PropertiesShouldNotBeWriteOnly", Scope = "member", Target = "LiveCapture.SMTPSender.#mailFrom" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage( "Microsoft.Design", "CA1044:PropertiesShouldNotBeWriteOnly", Scope = "member", Target = "LiveCapture.SMTPSender.#mailRcptTo" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage( "Microsoft.Design", "CA1044:PropertiesShouldNotBeWriteOnly", Scope = "member", Target = "LiveCapture.SMTPSender.#mailSentDate" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage( "Microsoft.Design", "CA1044:PropertiesShouldNotBeWriteOnly", Scope = "member", Target = "LiveCapture.SMTPSender.#mailSubject" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage( "Microsoft.Design", "CA1044:PropertiesShouldNotBeWriteOnly", Scope = "member", Target = "LiveCapture.SMTPSender.#mailTo" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage( "Microsoft.Design", "CA1044:PropertiesShouldNotBeWriteOnly", Scope = "member", Target = "LiveCapture.SMTPSender.#mailContentType" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage( "Microsoft.Performance", "CA1805:DoNotInitializeUnnecessarily", Scope = "member", Target = "LiveCapture.UcNotesClient.#.ctor()" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage( "Microsoft.Design", "CA1031:DoNotCatchGeneralExceptionTypes", Scope = "member", Target = "LiveCapture.UcTester.#importCSVData(System.String)" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage( "Microsoft.Design", "CA1031:DoNotCatchGeneralExceptionTypes", Scope = "member", Target = "LiveCapture.UcTester.#getDelimiterFormat()" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage( "Microsoft.Design", "CA1031:DoNotCatchGeneralExceptionTypes", Scope = "member", Target = "LiveCapture.UcTester.#connectCSV(System.String)" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage( "Microsoft.Design", "CA1031:DoNotCatchGeneralExceptionTypes", Scope = "member", Target = "LiveCapture.UcTester.#cboDelimiter_SelectionChangeCommitted(System.Object,System.EventArgs)" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage( "Microsoft.Performance", "CA1805:DoNotInitializeUnnecessarily", Scope = "member", Target = "LiveCapture.WinGenBloomData.#.ctor()" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage( "Microsoft.Design", "CA1031:DoNotCatchGeneralExceptionTypes", Scope = "member", Target = "LiveCapture.WinGenBloomData.#btnAbort_Click(System.Object,System.EventArgs)" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage( "Microsoft.Design", "CA1031:DoNotCatchGeneralExceptionTypes", Scope = "member", Target = "LiveCapture.WinGenBloomData.#btnCreate_Click(System.Object,System.EventArgs)" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage( "Microsoft.Design", "CA1031:DoNotCatchGeneralExceptionTypes", Scope = "member", Target = "LiveCapture.WinGenBloomData.#btnGenerate_Click(System.Object,System.EventArgs)" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage( "Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity", Scope = "member", Target = "LiveCapture.WinGenBloomData.#GenBloomCustomValue(System.String,System.Int32)" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage( "Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "LiveCapture.WinGenBloomData.#inXmlFullPathFN" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage( "Microsoft.Design", "CA1031:DoNotCatchGeneralExceptionTypes", Scope = "member", Target = "LiveCapture.WinGenDXLData.#Thd_GenDxlData()" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage( "Microsoft.Design", "CA1031:DoNotCatchGeneralExceptionTypes", Scope = "member", Target = "LiveCapture.WinGenDXLData.#LoadComboBoxes()" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage( "Microsoft.Design", "CA1031:DoNotCatchGeneralExceptionTypes", Scope = "member", Target = "LiveCapture.WinGenDXLData.#SaveComboBoxItem()" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage( "Microsoft.Design", "CA1031:DoNotCatchGeneralExceptionTypes", Scope = "member", Target = "LiveCapture.WinGenDXLData.#lnkNSFFile_LinkClicked(System.Object,System.Windows.Forms.LinkLabelLinkClickedEventArgs)" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage( "Microsoft.Design", "CA1031:DoNotCatchGeneralExceptionTypes", Scope = "member", Target = "LiveCapture.NameResolutionTest.#.ctor(System.Data.DataSet,System.String)" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage( "Microsoft.Design", "CA1031:DoNotCatchGeneralExceptionTypes", Scope = "member", Target = "LiveCapture.NameResolutionTest.#ProcessTest()" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage( "Microsoft.Performance", "CA1805:DoNotInitializeUnnecessarily", Scope = "member", Target = "Microsoft.Xml.XMLGen.InstanceGroup.#.ctor()" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage( "Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "Microsoft.Xml.XMLGen.InstanceElement.#Comment" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage( "Microsoft.Performance", "CA1805:DoNotInitializeUnnecessarily", Scope = "member", Target = "Microsoft.Xml.XMLGen.InstanceElement.#.ctor(System.Xml.XmlQualifiedName)" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage( "Microsoft.Performance", "CA1805:DoNotInitializeUnnecessarily", Scope = "member", Target = "Microsoft.Xml.XMLGen.InstanceElement.#.ctor()" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage( "Microsoft.Maintainability", "CA1501:AvoidExcessiveInheritance", Scope = "type", Target = "Microsoft.Xml.XMLGen.Generator_unsignedShort" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage( "Microsoft.Maintainability", "CA1501:AvoidExcessiveInheritance", Scope = "type", Target = "Microsoft.Xml.XMLGen.Generator_unsignedInt" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage( "Microsoft.Maintainability", "CA1501:AvoidExcessiveInheritance", Scope = "type", Target = "Microsoft.Xml.XMLGen.Generator_unsignedByte" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage( "Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "Microsoft.Xml.XMLGen.Generator_Union.#Generators" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage( "Microsoft.Reliability", "CA2001:AvoidCallingProblematicMethods", MessageId = "System.Type.InvokeMember", Scope = "member", Target = "Microsoft.Xml.XMLGen.Generator_Union.#GenerateValue()" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage( "Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors", Scope = "member", Target = "Microsoft.Xml.XMLGen.Generator_token.#.ctor(Microsoft.Xml.XMLGen.CompiledFacets)" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage( "Microsoft.Performance", "CA1805:DoNotInitializeUnnecessarily", Scope = "member", Target = "Microsoft.Xml.XMLGen.Generator_string.#.ctor(Microsoft.Xml.XMLGen.CompiledFacets)" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage( "Microsoft.Performance", "CA1805:DoNotInitializeUnnecessarily", Scope = "member", Target = "Microsoft.Xml.XMLGen.Generator_string.#.ctor()" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage( "Microsoft.Maintainability", "CA1501:AvoidExcessiveInheritance", Scope = "type", Target = "Microsoft.Xml.XMLGen.Generator_short" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage( "Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors", Scope = "member", Target = "Microsoft.Xml.XMLGen.Generator_QName.#.ctor(Microsoft.Xml.XMLGen.CompiledFacets)" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage( "Microsoft.Maintainability", "CA1501:AvoidExcessiveInheritance", Scope = "type", Target = "Microsoft.Xml.XMLGen.Generator_NMTOKEN" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage( "Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors", Scope = "member", Target = "Microsoft.Xml.XMLGen.Generator_NCName.#.ctor(Microsoft.Xml.XMLGen.CompiledFacets)" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage( "Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors", Scope = "member", Target = "Microsoft.Xml.XMLGen.Generator_Name.#.ctor(Microsoft.Xml.XMLGen.CompiledFacets)" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage( "Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "Microsoft.Xml.XMLGen.Generator_List.#ListLength" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage( "Microsoft.Performance", "CA1804:RemoveUnusedLocals", MessageId = "id", Scope = "member", Target = "Microsoft.Xml.XMLGen.Generator_IDREF.#GenerateValue()" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage( "Microsoft.Performance", "CA1805:DoNotInitializeUnnecessarily", Scope = "member", Target = "Microsoft.Xml.XMLGen.Generator_IDREF.#.ctor()" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage( "Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors", Scope = "member", Target = "Microsoft.Xml.XMLGen.Generator_ID.#.ctor()" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage( "Microsoft.Usage", "CA2201:DoNotRaiseReservedExceptionTypes", Scope = "member", Target = "Microsoft.Xml.XMLGen.Generator_hexBinary.#ProcessMinMaxLengthFacet(System.Text.StringBuilder&)" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage( "Microsoft.Usage", "CA2201:DoNotRaiseReservedExceptionTypes", Scope = "member", Target = "Microsoft.Xml.XMLGen.Generator_hexBinary.#ProcessLengthFacet(System.Text.StringBuilder&)" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage( "Microsoft.Performance", "CA1804:RemoveUnusedLocals", MessageId = "result", Scope = "member", Target = "Microsoft.Xml.XMLGen.Generator_gMonth.#GenerateValue()" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage( "Microsoft.Performance", "CA1805:DoNotInitializeUnnecessarily", Scope = "member", Target = "Microsoft.Xml.XMLGen.Generator_float.#.ctor(Microsoft.Xml.XMLGen.CompiledFacets)" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage( "Microsoft.Performance", "CA1805:DoNotInitializeUnnecessarily", Scope = "member", Target = "Microsoft.Xml.XMLGen.Generator_double.#.ctor(Microsoft.Xml.XMLGen.CompiledFacets)" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage( "Microsoft.Performance", "CA1805:DoNotInitializeUnnecessarily", Scope = "member", Target = "Microsoft.Xml.XMLGen.Generator_double.#.ctor()" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage( "Microsoft.Maintainability", "CA1501:AvoidExcessiveInheritance", Scope = "type", Target = "Microsoft.Xml.XMLGen.Generator_byte" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage( "Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors", Scope = "member", Target = "Microsoft.Xml.XMLGen.Generator_anyURI.#.ctor(Microsoft.Xml.XMLGen.CompiledFacets)" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage( "Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Microsoft.Xml.XMLGen.CompiledFacets.#XmlSchemaDatatypeType" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage( "Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "Microsoft.Xml.XMLGen.CompiledFacets.#WhiteSpace" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage( "Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "Microsoft.Xml.XMLGen.CompiledFacets.#Patterns" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage( "Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "Microsoft.Xml.XMLGen.CompiledFacets.#FixedFlags" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage( "Microsoft.Performance", "CA1810:InitializeReferenceTypeStaticFieldsInline", Scope = "member", Target = "Microsoft.Xml.XMLGen.CompiledFacets.#.cctor()" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage( "Microsoft.Design", "CA1031:DoNotCatchGeneralExceptionTypes", Scope = "member", Target = "LiveCapture.ZNotesEmlParser.#ReadEmlFile()" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage( "Microsoft.Design", "CA1031:DoNotCatchGeneralExceptionTypes", Scope = "member", Target = "LiveCapture.ZNotesEmlParser.#ParseEmlFile(System.String[])" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage( "Microsoft.Design", "CA1031:DoNotCatchGeneralExceptionTypes", Scope = "member", Target = "LiveCapture.ZNotesEmlParser.#getXZantazValue(System.String,System.String)" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage( "Microsoft.Design", "CA1031:DoNotCatchGeneralExceptionTypes", Scope = "member", Target = "LiveCapture.ZNotesEmlParser.#getXNotesItem(System.String,System.String)" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage( "Microsoft.Design", "CA1031:DoNotCatchGeneralExceptionTypes", Scope = "member", Target = "LiveCapture.WinZAData.#saveCSVFile(System.Data.DataSet,System.String)" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage( "Microsoft.Design", "CA1031:DoNotCatchGeneralExceptionTypes", Scope = "member", Target = "LiveCapture.WinZAData.#btnDoIt_Click(System.Object,System.EventArgs)" )]
